name: Maven Build and Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: test1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Maven
        run: mvn clean package


      - name: Verify JAR
        run: ls -l target/
